[project]
name = "chat-redis"
version = "0.1.0"
description = "Chat usando Redis para stream de mensagens"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "redis>=6.2.0",
    "textual>=0.40.0",
]
